Feature/screenshot manager
Softeq/SCAF pull request #28
Opened 2021-02-17 14:28 UTC by codci

* add screenshot manager for wed and mobile parts

2021-02-17 15:45 UTC, maximrodin requested changes

2021-02-17 15:45 UTC, maximrodin commented on common/_libs/logger.py
> +    def base_log_path(self):
Need to normalize it and define it as a class field or instance field, not just raw property without a definition.

2021-02-17 15:45 UTC, maximrodin commented on common/_webdriver_qa_api/core/screenshot_manager.py
> +        if not screenshot_name:
need to use slugify function if we expect to pass test name here, because it may contain unexpected characters for win platform

2021-02-18 08:46 UTC, codci commented on common/_libs/logger.py
> +    def base_log_path(self):
done

2021-02-18 08:46 UTC, codci commented on common/_webdriver_qa_api/core/screenshot_manager.py
> +        if not screenshot_name:
done

2021-02-18 11:49 UTC, maximrodin reviewed
Please remove import os and get_timestamp from common/_libs/logger.py

2021-02-18 12:11 UTC, maximrodin approved these changes

2021-02-18 12:11 UTC, merged